berita/urls.py
from django.urls import path

from . import views

app_name = 'berita'

urlpatterns = [
    path('', views.home, name='home'),
]

formSaran/urls.py
from django.urls import path

from . import views

app_name = 'formSaran'

urlpatterns = [
    path('', views.saran, name='saran'),
    path('create/', views.create, name='create'),
    path('list1/', views.list1, name='list1'),
]

kepepetpergi/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('berita/', include('berita.urls')),
    path('formSaran/', include('formSaran.urls')),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

berita/models.py
from django.db import models

# Create your models here.

formSaran/models.py
# from django.db import models

# # Create your models here.

# class PostModel(models.Model):
#     email = models.CharField(max_length = 100)
#     LIST_SARAN = (
#         ('perbaikan website','Perbaikan website'),
#         ('masukkan data provinsi','Masukkan data provinsi'),
#         )
#     jenis_saran = models.CharField(
#             max_length = 100,
#             choices = LIST_SARAN,
#             default = 'perbaikan website',
#             )
#     keterangan  = models.TextField()
    

        

#     def __str__(self):
#         return self.email

main/models.py
from django.db import models
from datetime import datetime, date
# Create your models here.

# Province Data
class Pulau(models.Model):
    nama = models.CharField(max_length=35, primary_key=True)

class Provinsi(models.Model):
    nama = models.CharField(max_length=35, null=False)
    nama_pulau = models.ForeignKey(Pulau, on_delete=models.CASCADE, related_name='provinsi', null=False)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['nama', 'nama_pulau'], name='composite primary key constraint provinsi')
        ]

class Info(models.Model):
    info_id = models.AutoField(primary_key=True)
    tanggal = models.DateField()
    nama_provinsi = models.ForeignKey(Provinsi, on_delete=models.CASCADE, related_name='info', null=False)
    protokol_kesehatan = models.TextField()

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['info_id', 'nama_provinsi'], name='composite primary key constraint info')
        ]

class WebsitePemda(models.Model):
    info_id = models.ForeignKey(Info, on_delete=models.CASCADE, related_name='website_pemda', null=False)
    alamat = models.URLField(null=False)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['info_id', 'alamat'], name='composite primary key constraint website pemda')
        ]

class EmailPemda(models.Model):
    info_id = models.ForeignKey(Info, on_delete=models.CASCADE, related_name='email_pemda', null=False)
    email = models.CharField(max_length=35, null=False)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['info_id', 'email'], name='composite primary key constraint email pemda')
        ]

class TelponPemda(models.Model):
    info_id = models.ForeignKey(Info, on_delete=models.CASCADE, related_name='telpon_pemda', null=False)
    nomor_telpon = models.CharField(max_length=20, null=False)
    
    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['info_id', 'nomor_telpon'], name='composite primary key constraint telpon pemda')
        ]

class VerifiedInfo(models.Model):
    info_id = models.ForeignKey(Info, on_delete=models.CASCADE, related_name='verified', primary_key=True)

class NonVerifiedInfo(models.Model):
    info_id = models.ForeignKey(Info, on_delete=models.CASCADE, related_name='non_verified', null=False)
    email = models.CharField(max_length=35, null=False)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['info_id', 'email'], name='composite primary key constraint non verified info')
        ]

# Feedback Data
class Saran(models.Model):
    SARAN_CHOICES = (
        ('P', 'Perbaikan website'),
        ('M', 'Masukkan data provinsi')
    )

    saran_id = models.AutoField(primary_key=True)
    tanggal = models.DateField(auto_now_add = False, auto_now = False, blank = True,null = True)
    timestamp = models.DateField(auto_now_add=True, auto_now=False,blank = True)
    email = models.CharField(max_length=35)
    jenis_saran = models.CharField(max_length=1, choices=SARAN_CHOICES)
    saran = models.TextField()

formSaran/forms.py
from django import forms

from main.models import Saran

class PostForm(forms.ModelForm):
    class Meta:
        model = Saran
        fields =[
            'email',
            'jenis_saran',
            'saran',
   
            
        ]

        widgets = {
            'email': forms.TextInput(
                attrs = {
                    'class': 'form-control',
                    'placeholder' : 'isi dengan email anda',
                }    
            ),
            'jenis_saran': forms.Select(
                attrs = {
                    'class': 'form-control',
                    'placeholder' : 'isi keterangannya',
                }
            ),
            'saran': forms.Textarea(
                attrs = {
                    'class': 'form-control',
                    
                }
            ),


        }

berita/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'berita/home.html')

formSaran/views.py
from main.models import Saran
from django.shortcuts import render,redirect


from .forms import PostForm

# Create your views here.
def saran(request):
    context = {
        'page_title':'Home',

    }
    return render(request,'saran.html',context)

def list1(request):
    posts = Saran.objects.all()

    context = {
        'page_title':'Semua Post',
        'posts':posts,
    }
    print(posts)
    return render(request,'formSaran/list1.html',context)

def create(request):
    post_form = PostForm(request.POST or None)

    if request.method == 'POST' :#post request dari browser
        if post_form.is_valid():
            post_form.save()

            return redirect('formSaran:list1')

    context = {
        'page_title':'Create Post',
        'post_form': post_form
    }
    return render(request,'formSaran/create.html',context)

main/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'main/home.html')

pencarian/views.py
from django.shortcuts import render

# Create your views here.

berita/templates/berita/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Berita</title>
{% endblock meta %}

{% block footer_style %}relative{% endblock %}

{% block content %}

  <div class="d-flex flex-column my-3">
    <h1 style="text-align: center;"> Berita </h1>

    <div class="card my-5 border-custom">
      <div class="card-body p-5">
        <h5 class="card-title">Card title</h5>
        <div class="card my-3 border-custom2">
          <div class="card-body child-card">
            <img class="img-fluid rounded image-custom" src="{% static 'img/download.jpg' %}" alt="Card image cap">
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          </div>
        </div>
        <p class="float-right">Sumber: <a href="#" class="card-link">Another link</a></p>
      </div>
    </div>

    <div class="card my-5 border-custom">
      <div class="card-body p-5">
        <h5 class="card-title">Card title</h5>
        <div class="card my-3 border-custom2">
          <div class="card-body child-card">
            <img class="img-fluid rounded image-custom" src="{% static 'img/download.jpg' %}" alt="Card image cap">
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          </div>
        </div>
        <p class="float-right">Sumber: <a href="#" class="card-link">Another link</a></p>
      </div>
    </div>

    <div class="card my-5 border-custom">
      <div class="card-body p-5">
        <h5 class="card-title">Card title</h5>
        <div class="card my-3 border-custom2">
          <div class="card-body child-card">
            <img class="img-fluid rounded image-custom" src="{% static 'img/download.jpg' %}" alt="Card image cap">
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          </div>
        </div>
        <p class="float-right">Sumber: <a href="#" class="card-link">Another link</a></p>
      </div>
    </div>

  </div>

{% endblock content %}

formSaran/templates/formSaran/create.html
{% extends 'base.html' %}
{% load static %}
<!-- Required meta tags -->

{% block meta %}
<title>{{page_title}}</title>
{% endblock meta %}

{% block footer_style %}relative{% endblock %}

{% block content %}


    <div class="d-flex flex-column my-3">
        <h1 style="text-align: center;"> {{page_title}} </h1>
    <div class="card my-5 border-custom">
      <div class="card-body p-5">
        <h5 class="card-title">{{page_title}}</h5>
        <div class="card my-3 border-custom2">
          <div class="card-body child-card">
            <form method = 'POST'>
                {%csrf_token%}
                {%for form in post_form%}
            
                    <div class = "form-group">
                        {{form.label}}
                        {{form}}
                    </div>
                
                    
                {%endfor%}
                <button type = "Submit">Kirim</button>
            
                </form>

          </div>
        </div>

      </div>
    </div>
   
   

  

{% endblock content %}

formSaran/templates/formSaran/list1.html
{% extends 'base.html' %}
{% load static %}
<!-- Required meta tags -->


{% block title %}
    <h1>{{page_title}}</h1>
{% endblock title %}


{% block content %}
    <h1>{{page_title}}</h1>
    <br>
    {% for post in posts%}

        <h1>{{post.email}}</h1>
        <h5>jenis : {{post.jenis_saran}}</h5>
        <p>{{post.saran}}</p>
    {%endfor%}
  

{% endblock content %}

formSaran/templates/saran.html
{% extends 'base.html' %}
{% load static %}
<!-- Required meta tags -->


{% block meta %}
    <h1>{{page_title}}</h1>
{% endblock meta %}


{% block content %}

  

{% endblock content %}

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block footer_style %}fixed{% endblock %}

{% block content %}
  <h1>Hello, world!</h1>
  <p><img src="{% static 'img/django-logo-negative.svg' %}"></p>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
  
</head>

<body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'main:home' %}">Navbar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'main:home' %}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="#">Pencarian <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="#">Status <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'berita:home' %}">Berita <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Bantu Kami
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'formSaran:create' %}">Kesalanan Data</a>
              <a class="dropdown-item" href="#">Saran Penambahan Data</a>
            </div>
            <li class="nav-item active">
              <a class="nav-link" href="#">Contact Us <span class="sr-only">(current)</span></a>
            </li>
          </li>
        </ul>
      </div>
    </nav>
  </header>
  {% block content %}
  {% endblock content %}
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
<!-- Footer -->
<footer class="page-footer font-small blue pt-4" style="position: {% block footer_style %}{% endblock %};left: 0;bottom: 0; width: 100%;">

  <!-- Footer Links -->
  <div class="container-fluid text-center text-md-left">

    <!-- Grid row -->
    <div class="row">

      <!-- Grid column -->
      <div class="col-md-6 mt-md-0 mt-3">

        <!-- Content -->
        <h5 class="text-uppercase">Footer Content</h5>
        <p>Here you can use rows and columns to organize your footer content.</p>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none pb-3">

      <!-- Grid column -->
      <div class="col-md-3 mb-md-0 mb-3">

        <!-- Links -->
        <h5 class="text-uppercase">Links</h5>

        <ul class="list-unstyled">
          <li>
            <a href="#!">Link 1</a>
          </li>
          <li>
            <a href="#!">Link 2</a>
          </li>
          <li>
            <a href="#!">Link 3</a>
          </li>
          <li>
            <a href="#!">Link 4</a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-3 mb-md-0 mb-3">

        <!-- Links -->
        <h5 class="text-uppercase">Links</h5>

        <ul class="list-unstyled">
          <li>
            <a href="#!">Link 1</a>
          </li>
          <li>
            <a href="#!">Link 2</a>
          </li>
          <li>
            <a href="#!">Link 3</a>
          </li>
          <li>
            <a href="#!">Link 4</a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Links -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="https://mdbootstrap.com/"> MDBootstrap.com</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->
</body>


</html>